sudo: false
language: ruby

rvm:
  - 2.1.5
  - 2.2.4
  - 2.3.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake dummy:prepare
  - bundle exec rspec

addons:
  code_climate:
    repo_token: fa6eecd14a238a6a4326b5b001bab6b0acf5170da237779800fa4935ad1c0026